server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-api-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: email-api-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/email/**
