server.port=8080

spring.cloud.gateway.routes[0].id=user-api-route
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.routes[1].id=email-api-route
spring.cloud.gateway.routes[1].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/email/**

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=DEBUG
logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping=DEBUG
logging.level.reactor.netty.http.client=DEBUG
